In [2]:
import pandas as pd
import json

In [4]:
file_provinsi = {
    'jumlah_penduduk_gorontalo.csv': 'gorontalo',
    'jumlah_penduduk_sulawesi_barat.csv': 'sulawesi_barat',
    'jumlah_penduduk_sulawesi_selatan.csv': 'sulawesi_selatan',
    'jumlah_penduduk_sulawesi_tengah.csv' : 'sulawesi_tengah',
    'jumlah_penduduk_sulawesi_tenggara.csv': 'sulawesi_tenggara',
    'jumlah_penduduk_sulawesi_utara.csv': 'sulawesi_utara'
}

list_df = []

for filename, provinsi in file_provinsi.items():
    df_merge = pd.read_csv(filename)
    df_flat = pd.DataFrame([{
        'provinsi': provinsi,
        'laki_laki': int(df_merge['laki_laki'].iloc[0]),
        'perempuan': int(df_merge['perempuan'].iloc[0]),
        'total_keseluruhan': int(df_merge['total_keseluruhan'].iloc[0])
    }])
    list_df.append(df_flat)

df_merge_sulawesi = pd.concat(list_df, ignore_index=True)

display(df_merge_sulawesi)

            provinsi  laki_laki  perempuan  total_keseluruhan
0          gorontalo     626100     616200            1242300
1     sulawesi_barat     772700     752700            1525400
2   sulawesi_selatan    4702000    4811300            9513300
3    sulawesi_tengah    1617200    1538900            3156100
4  sulawesi_tenggara    1436300    1400500            2836800
5     sulawesi_utara    1388200    1333200            2721400

In [6]:
total_laki_gabungan = int(df_merge_sulawesi['laki_laki'].sum())
total_perempuan_gabungan = int(df_merge_sulawesi['perempuan'].sum())
total_gabungan_keseluruhan = int(df_merge_sulawesi['total_keseluruhan'].sum())

df_total_pulau = pd.DataFrame([{
    'provinsi': 'total_pulau_sulawesi',
    'laki_laki': total_laki_gabungan,
    'perempuan': total_perempuan_gabungan,
    'total_keseluruhan': total_gabungan_keseluruhan
}])

df_final = pd.concat([df_merge_sulawesi, df_total_pulau], ignore_index=True)

display(df_final)

               provinsi  laki_laki  perempuan  total_keseluruhan
0             gorontalo     626100     616200            1242300
1        sulawesi_barat     772700     752700            1525400
2      sulawesi_selatan    4702000    4811300            9513300
3       sulawesi_tengah    1617200    1538900            3156100
4     sulawesi_tenggara    1436300    1400500            2836800
5        sulawesi_utara    1388200    1333200            2721400
6  total_pulau_sulawesi   10542500   10452800           20995300

In [7]:
df_final.to_csv('data_penduduk_sulawesi.csv', index=False)
df_final.to_json('data_penduduk_sulawesi.json', orient='records')

In [8]:
total_laki_pulau = 0
total_perempuan_pulau = 0

for filename in file_provinsi:
    df_temp = pd.read_csv(filename)
    total_laki_pulau += int(df_temp['laki_laki'].iloc[0])
    total_perempuan_pulau += int(df_temp['perempuan'].iloc[0])

total_keseluruhan_pulau = total_laki_pulau + total_perempuan_pulau

df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_pulau_sulawesi',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

json_output = df_final_pulau.to_json('data_gabungan_sulawesi.json', orient='records')
print(json_output)

csv_output = df_final_pulau.to_csv('data_gabungan_sulawesi.csv', index=False)
display(df_final_pulau)

None

             keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_sulawesi   10542500   10452800           20995300