In [64]:
import pandas as pd

# baca data
data = pd.read_csv(
    "Data_Jambi_Kotor.csv",
    sep=';'
)

display(data.head())

  kelompok_umur jenis_kelamin Unnamed: 2
0           NaN     Laki-laki  Perempuan
1           0-4        164.77     159.55
2          '5-9        158.89     152.54
3         10-14        158.66     151.81
4        '15-19        155.59     146.74

In [67]:
import pandas as pd

data = pd.read_csv(
    "Data_Jambi_Kotor.csv",
    sep=';'
)

df = data.copy()

df.columns = [
    'kelompok_umur',
    'laki_laki',
    'perempuan'
]

display(df.head())

df_jumlah = df[
    df['kelompok_umur'].astype(str).str.contains(
        'Jumlah/Total',
        na=False
    )
]

total_laki = int(
    float(df_jumlah.iloc[0,1]) * 1000
)

total_perempuan = int(
    float(df_jumlah.iloc[0,2]) * 1000
)

total_keseluruhan = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

df_final.to_csv(
    'jumlah_penduduk_jambi.csv',
    index=False
)

df_final.to_json(
    'jumlah_penduduk_jambi.json',
    orient='records',
    indent=4
)

  kelompok_umur  laki_laki  perempuan
0           NaN  Laki-laki  Perempuan
1           0-4     164.77     159.55
2          '5-9     158.89     152.54
3         10-14     158.66     151.81
4        '15-19     155.59     146.74

   laki_laki  perempuan  total_keseluruhan
0    1914250    1854230            3768480