In [1]:
import pandas as pd

# baca data
data = pd.read_csv(
    "Data_Sumatera_Selatan_Kotor.csv",
    sep=';'
)

display(data.head())

  Kabupaten/Kota 17,Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten/Kota (Hasil SP2020) (Jiwa),
0                               ,Laki-Laki,Perempuan
1                                         ,2025,2025
2                   Sumatera Selatan,4542623,4385892
3                    Ogan Komering Ulu,197773,189043
4                   Ogan Komering Ilir,418678,397827

In [3]:
import pandas as pd

data = pd.read_csv("Data_Sumatera_Selatan_Kotor.csv")

display(data.head())
print(data.columns)

,Kabupaten/Kota 17,Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten/Kota (Hasil SP2020) (Jiwa),Unnamed: 2
0,NaN,Laki-Laki,Perempuan
1,NaN,2025,2025
2,Sumatera Selatan,4542623,4385892
3,Ogan Komering Ulu,197773,189043
4,Ogan Komering Ilir,418678,397827

Index(['Kabupaten/Kota 17',
       'Jumlah Penduduk Menurut Jenis Kelamin dan Kabupaten/Kota (Hasil SP2020) (Jiwa)',
       'Unnamed: 2'],
      dtype='object')

In [4]:
import pandas as pd


data = pd.read_csv("Data_Sumatera_Selatan_Kotor.csv")

df = data.copy()

total_laki = int(df.iloc[2,1])

total_perempuan = int(df.iloc[2,2])

total_keseluruhan = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

# simpan csv
df_final.to_csv(
    'jumlah_penduduk_sumatera_selatan.csv',
    index=False
)

# simpan json
df_final.to_json(
    'jumlah_penduduk_sumatera_selatan.json',
    orient='records',
    indent=4
)

   laki_laki  perempuan  total_keseluruhan
0    4542623    4385892            8928515