In [13]:
import pandas as pd

aceh = pd.read_csv("jumlah_penduduk_aceh.csv")
sumatera_utara = pd.read_csv("jumlah_penduduk_sumatera_utara.csv")
sumatera_barat = pd.read_csv("jumlah_penduduk_sumatera_barat.csv")
riau = pd.read_csv("jumlah_penduduk_riau.csv")
jambi = pd.read_csv("jumlah_penduduk_jambi.csv")
sumatera_selatan = pd.read_csv("jumlah_penduduk_sumatera_selatan.csv")
bengkulu = pd.read_csv("jumlah_penduduk_bengkulu.csv")
lampung = pd.read_csv("jumlah_penduduk_lampung.csv")
bangka_belitung = pd.read_csv("jumlah_penduduk_bangka_belitung.csv")
kepulauan_riau = pd.read_csv("jumlah_penduduk_kepulauan_riau.csv")

sumatera = pd.concat([
    aceh,
    sumatera_utara,
    sumatera_barat,
    riau,
    jambi,
    sumatera_selatan,
    bengkulu,
    lampung,
    bangka_belitung,
    kepulauan_riau
])

display(sumatera)

sumatera.to_csv(
    'data_penduduk_sumatera.csv',
    index=False
)

sumatera.to_json(
    'data_penduduk_sumatera.json',
    orient='records',
    indent=4
)

   laki_laki  perempuan  total_keseluruhan        provinsi
0    2825512    2800448            5625960             NaN
0    7862993    7922846           15785839             NaN
0    2979710    2934590            5914300  Sumatera Barat
0    3476706    3334452            6811158             NaN
0    1914250    1854230            3768480             NaN
0    4542623    4385892            8928515             NaN
0    1091256    1046788            2138044             NaN
0    4857470    4665440            9522910             NaN
0     795930     756450            1552380             NaN
0    1322950    1271410            2594360             NaN

In [17]:
import pandas as pd

# contoh gabungan data provinsi
gabungan = pd.DataFrame({
    'provinsi': [
        'Aceh',
        'Sumatera Utara',
        'Sumatera Barat',
        'Riau',
        'Jambi',
        'Sumatera Selatan',
        'Bengkulu',
        'Lampung',
        'Kepulauan Bangka Belitung',
        'Kepulauan Riau'
    ],

    'laki_laki': [
        2825512,
        7862993,
        2979710,
        3476706,
        1914250,
        4542623,
        1091256,
        4857470,
        795930,
        1322950
    ],

    'perempuan': [
        2800448,
        7922846,
        2934590,
        3334452,
        1854230,
        4385892,
        1046788,
        4665440,
        756450,
        1271410
    ]
})

# total keseluruhan
gabungan['total_keseluruhan'] = (
    gabungan['laki_laki'] +
    gabungan['perempuan']
)

# rapihin urutan kolom
gabungan = gabungan[
    [
        'provinsi',
        'laki_laki',
        'perempuan',
        'total_keseluruhan'
    ]
]

# tampilkan hasil
print(gabungan)

# save csv
gabungan.to_csv(
    'data_penduduk_sumatera.csv',
    index=False
)

# save json
gabungan.to_json(
    'data_penduduk_sumatera.json',
    orient='records',
    indent=4
)

print("File gabungan CSV dan JSON berhasil disimpan!")

                    provinsi  laki_laki  perempuan  total_keseluruhan
0                       Aceh    2825512    2800448            5625960
1             Sumatera Utara    7862993    7922846           15785839
2             Sumatera Barat    2979710    2934590            5914300
3                       Riau    3476706    3334452            6811158
4                      Jambi    1914250    1854230            3768480
5           Sumatera Selatan    4542623    4385892            8928515
6                   Bengkulu    1091256    1046788            2138044
7                    Lampung    4857470    4665440            9522910
8  Kepulauan Bangka Belitung     795930     756450            1552380
9             Kepulauan Riau    1322950    1271410            2594360
File gabungan CSV dan JSON berhasil disimpan!

In [19]:
import pandas as pd

file_provinsi = [
    'jumlah_penduduk_aceh.csv',
    'jumlah_penduduk_sumatera_utara.csv',
    'jumlah_penduduk_sumatera_barat.csv',
    'jumlah_penduduk_riau.csv',
    'jumlah_penduduk_jambi.csv',
    'jumlah_penduduk_sumatera_selatan.csv',
    'jumlah_penduduk_bengkulu.csv',
    'jumlah_penduduk_lampung.csv',
    'jumlah_penduduk_bangka_belitung.csv',
    'jumlah_penduduk_kepulauan_riau.csv'
]

# total awal
total_laki_pulau = 0
total_perempuan_pulau = 0

# looping file
for filename in file_provinsi:

    df_temp = pd.read_csv(filename)

    total_laki_pulau += int(
        df_temp['laki_laki'].iloc[0]
    )

    total_perempuan_pulau += int(
        df_temp['perempuan'].iloc[0]
    )

# total keseluruhan
total_keseluruhan_pulau = (
    total_laki_pulau +
    total_perempuan_pulau
)

# dataframe final
df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_pulau_sumatera',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

# tampilkan
display(df_final_pulau)

# save json
df_final_pulau.to_json(
    'data_gabungan_sumatera.json',
    orient='records',
    indent=4
)

# save csv
df_final_pulau.to_csv(
    'data_gabungan_sumatera.csv',
    index=False
)

print("File gabungan Sumatera berhasil disimpan!")

             keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_sumatera   31669400   30972546           62641946

File gabungan Sumatera berhasil disimpan!