In [ ]:
import pandas as pd

aceh = pd.read_csv("jumlah_penduduk_aceh.csv")
sumut = pd.read_csv("jumlah_penduduk_sumatera_utara.csv")
sumbar = pd.read_csv("jumlah_penduduk_sumatera_barat.csv")
riau = pd.read_csv("jumlah_penduduk_riau.csv")
jambi = pd.read_csv("jumlah_penduduk_jambi.csv")
sumsel = pd.read_csv("jumlah_penduduk_sumatera_selatan.csv")
bengkulu = pd.read_csv("jumlah_penduduk_bengkulu.csv")
lampung = pd.read_csv("jumlah_penduduk_lampung.csv")

sumatera = pd.concat([
    aceh,
    sumut,
    sumbar,
    riau,
    jambi,
    sumsel,
    bengkulu,
    lampung
])

display(sumatera)

sumatera.to_csv(
    'data_penduduk_sumatera.csv',
    index=False
)

sumatera.to_json(
    'data_penduduk_sumatera.json',
    orient='records',
    indent=4
)

   laki_laki  perempuan  total_keseluruhan
0    2825512    2800448            5625960
0    7862993    7922846           15785839
0       2979       2934               5913
0    3476706    3334452            6811158
0    1914250    1854230            3768480
0    4542623    4385892            8928515
0    1091256    1046788            2138044
0    4857470    4665440            9522910

In [67]:
import pandas as pd

file_provinsi = [
    'jumlah_penduduk_aceh.csv',
    'jumlah_penduduk_sumatera_utara.csv',
    'jumlah_penduduk_sumatera_barat.csv',
    'jumlah_penduduk_riau.csv',
    'jumlah_penduduk_jambi.csv',
    'jumlah_penduduk_sumatera_selatan.csv',
    'jumlah_penduduk_bengkulu.csv',
    'jumlah_penduduk_lampung.csv'
]
data_sumatera = []


total_laki = 0
total_perempuan = 0


for file in file_provinsi:

    df = pd.read_csv(file)

    laki = int(df['laki_laki'].iloc[0])
    perempuan = int(df['perempuan'].iloc[0])
    total = int(df['total_keseluruhan'].iloc[0])

    nama_provinsi = file.replace('.csv', '')


    data_sumatera.append({
        'provinsi': nama_provinsi,
        'laki_laki': laki,
        'perempuan': perempuan,
        'total_keseluruhan': total
    })


    total_laki += laki
    total_perempuan += perempuan


total_pulau = total_laki + total_perempuan


data_sumatera.append({
    'provinsi': 'total_pulau_sumatera',
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_pulau
})


df_final = pd.DataFrame(data_sumatera)

display(df_final)


df_final.to_csv(
    'data_penduduk_sumatera.csv',
    index=False
)


df_final.to_json(
    'data_penduduk_sumatera.json',
    orient='records',
    indent=4
)

                           provinsi  laki_laki  perempuan  total_keseluruhan
0              jumlah_penduduk_aceh    2825512    2800448            5625960
1    jumlah_penduduk_sumatera_utara    7862993    7922846           15785839
2    jumlah_penduduk_sumatera_barat       2979       2934               5913
3              jumlah_penduduk_riau    3476706    3334452            6811158
4             jumlah_penduduk_jambi    1914250    1854230            3768480
5  jumlah_penduduk_sumatera_selatan    4542623    4385892            8928515
6          jumlah_penduduk_bengkulu    1091256    1046788            2138044
7           jumlah_penduduk_lampung    4857470    4665440            9522910
8              total_pulau_sumatera   26573789   26013030           52586819

In [65]:
import pandas as pd

file_provinsi = [
    'jumlah_penduduk_aceh.csv',
    'jumlah_penduduk_sumatera_utara.csv',
    'jumlah_penduduk_sumatera_barat.csv',
    'jumlah_penduduk_riau.csv',
    'jumlah_penduduk_jambi.csv',
    'jumlah_penduduk_sumatera_selatan.csv',
    'jumlah_penduduk_bengkulu.csv',
    'jumlah_penduduk_lampung.csv'
]


total_laki_pulau = 0
total_perempuan_pulau = 0


for filename in file_provinsi:
    df_temp = pd.read_csv(filename)

    total_laki_pulau += int(
        df_temp['laki_laki'].iloc[0]
    )

    total_perempuan_pulau += int(
        df_temp['perempuan'].iloc[0]
    )


total_keseluruhan_pulau = (
    total_laki_pulau + total_perempuan_pulau
)

# dataframe final pulau
df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_pulau_sumatera',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

display(df_final_pulau)


df_final_pulau.to_json(
    'data_gabungan_sumatera.json',
    orient='records',
    indent=4
)


df_final_pulau.to_csv(
    'data_gabungan_sumatera.csv',
    index=False
)

             keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_sumatera   26573789   26013030           52586819