In [38]:
import pandas as pd

laki = pd.read_csv(
    "Data_Kalimantan_Utara_Laki_Laki_Kotor.csv",
    sep=','
)

perempuan = pd.read_csv(
    "Data_Kalimantan_Utara_Perempuan_Kotor.csv",
    sep=','
)

df_gabung = pd.DataFrame({
    'wilayah': [
        'Malinau',
        'Bulungan',
        'Tana Tidung',
        'Nunukan',
        'Tarakan',
        'Kalimantan Utara'
    ],

    'laki_laki': [
        45191,
        81490,
        14536,
        110643,
        137359,
        389219
    ],

    'perempuan': [
        41119,
        76228,
        13597,
        101001,
        124292,
        356237
    ]
})

display(df_gabung)


df_gabung.to_csv(
    'Data_Kalimantan_Utara_Gabungan.csv',
    index=False
)

            wilayah  laki_laki  perempuan
0           Malinau      45191      41119
1          Bulungan      81490      76228
2       Tana Tidung      14536      13597
3           Nunukan     110643     101001
4           Tarakan     137359     124292
5  Kalimantan Utara     389219     356237

In [40]:
import pandas as pd


data = pd.read_csv(
    "Data_Kalimantan_Utara_Gabungan.csv"
)

display(data)

total_laki = int(data.iloc[5,1])

total_perempuan = int(data.iloc[5,2])


total_keseluruhan = (
    total_laki + total_perempuan
)


df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

# simpan csv final
df_final.to_csv(
    'jumlah_penduduk_kalimantan_utara.csv',
    index=False
)

# simpan json
df_final.to_json(
    'jumlah_penduduk_kalimantan_utara.json',
    orient='records',
    indent=4
)

            wilayah  laki_laki  perempuan
0           Malinau      45191      41119
1          Bulungan      81490      76228
2       Tana Tidung      14536      13597
3           Nunukan     110643     101001
4           Tarakan     137359     124292
5  Kalimantan Utara     389219     356237

   laki_laki  perempuan  total_keseluruhan
0     389219     356237             745456