In [1]:
import pandas as pd
import json

In [5]:
file_provinsi = {
   'jumlah_penduduk_maluku.csv': 'maluku',
   'jumlah_penduduk_maluku_utara.csv': 'maluku_utara'
}

list_df = []

for filename, provinsi in file_provinsi.items():
    df_merge = pd.read_csv(filename)
    df_flat = pd.DataFrame([{
        'provinsi': provinsi,
        'laki_laki': int(df_merge['laki_laki'].iloc[0]),
        'perempuan': int(df_merge['perempuan'].iloc[0]),
        'total_keseluruhan': int(df_merge['total_keseluruhan'].iloc[0])
    }])
    list_df.append(df_flat)

df_merge_maluku = pd.concat(list_df, ignore_index=True)

display(df_merge_maluku)

       provinsi  laki_laki  perempuan  total_keseluruhan
0        maluku     996167     974396            1970563
1  maluku_utara     704000     669800            1373800

In [6]:
total_laki_gabungan = int(df_merge_maluku['laki_laki'].sum())
total_perempuan_gabungan = int(df_merge_maluku['perempuan'].sum())
total_gabungan_keseluruhan = int(df_merge_maluku['total_keseluruhan'].sum())

df_total_pulau = pd.DataFrame([{
    'provinsi': 'total_pulau_maluku',
    'laki_laki': total_laki_gabungan,
    'perempuan': total_perempuan_gabungan,
    'total_keseluruhan': total_gabungan_keseluruhan
}])

df_final = pd.concat([df_merge_maluku, df_total_pulau], ignore_index=True)

display(df_final)

             provinsi  laki_laki  perempuan  total_keseluruhan
0              maluku     996167     974396            1970563
1        maluku_utara     704000     669800            1373800
2  total_pulau_maluku    1700167    1644196            3344363

In [7]:
df_final.to_csv('data_penduduk_maluku.csv', index=False)
df_final.to_json('data_penduduk_maluku.json', orient='records')

In [10]:
total_laki_pulau = 0
total_perempuan_pulau = 0

for filename in file_provinsi:
    df_temp = pd.read_csv(filename)
    total_laki_pulau += int(df_temp['laki_laki'].iloc[0])
    total_perempuan_pulau += int(df_temp['perempuan'].iloc[0])

total_keseluruhan_pulau = total_laki_pulau + total_perempuan_pulau

df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_pulau_maluku',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

json_output = df_final_pulau.to_json('data_gabungan_maluku.json', orient='records')
print(json_output)

csv_output = df_final_pulau.to_csv('data_gabungan_maluku.csv', index=False)
display(df_final_pulau)

None

           keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_maluku    1700167    1644196            3344363