In [1]:
import pandas as pd
import json

In [2]:
file_provinsi = {
    "jumlah_penduduk_papua.csv": "papua",
    "jumlah_penduduk_papua_barat.csv": "papua_barat",
    "jumlah_penduduk_papua_barat_daya.csv": "papua_barat_daya",
    "jumlah_penduduk_papua_pegunungan.csv": "papua_pegunungan",
    "jumlah_penduduk_papua_selatan.csv": "papua_selatan",
    "jumlah_penduduk_papua_tengah.csv": "papua_tengah"
}

list_df = []

for filename, provinsi in file_provinsi.items():
    df_merge = pd.read_csv(filename)
    df_flat = pd.DataFrame([{
        'provinsi': provinsi,
        'laki_laki': int(df_merge['laki_laki'].iloc[0]),
        'perempuan': int(df_merge['perempuan'].iloc[0]),
        'total_keseluruhan': int(df_merge['total_keseluruhan'].iloc[0])
    }])
    list_df.append(df_flat)

df_merge_papua = pd.concat(list_df, ignore_index=True)

display(df_merge_papua)

           provinsi  laki_laki  perempuan  total_keseluruhan
0             papua     560900     512700            1073600
1       papua_barat     308424     279221             587645
2  papua_barat_daya     331210     305230             636440
3  papua_pegunungan     791080     693780            1484860
4     papua_selatan     285030     264610             549640
5      papua_tengah     793490     698850            1492340

In [6]:
total_laki_gabungan = int(df_merge_papua['laki_laki'].sum())
total_perempuan_gabungan = int(df_merge_papua['perempuan'].sum())
total_gabungan_keseluruhan = int(df_merge_papua['total_keseluruhan'].sum())

df_total_pulau = pd.DataFrame([{
    'provinsi': 'total_pulau_papua',
    'laki_laki': total_laki_gabungan,
    'perempuan': total_perempuan_gabungan,
    'total_keseluruhan': total_gabungan_keseluruhan
}])

df_final = pd.concat([df_merge_papua, df_total_pulau], ignore_index=True)

display(df_final)

            provinsi  laki_laki  perempuan  total_keseluruhan
0              papua     560900     512700            1073600
1        papua_barat     308424     279221             587645
2   papua_barat_daya     331210     305230             636440
3   papua_pegunungan     791080     693780            1484860
4      papua_selatan     285030     264610             549640
5       papua_tengah     793490     698850            1492340
6  total_pulau_papua    3070134    2754391            5824525

In [7]:
df_final.to_csv('data_penduduk_papua.csv', index=False)
df_final.to_json('data_penduduk_papua.json', orient='records')

In [5]:
total_laki_pulau = 0
total_perempuan_pulau = 0

for filename in file_provinsi:
    df_temp = pd.read_csv(filename)
    total_laki_pulau += int(df_temp['laki_laki'].iloc[0])
    total_perempuan_pulau += int(df_temp['perempuan'].iloc[0])

total_keseluruhan_pulau = total_laki_pulau + total_perempuan_pulau

df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_pulau_papua',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

json_output = df_final_pulau.to_json('data_gabungan_papua.json', orient='records')
print(json_output)

csv_output = df_final_pulau.to_csv('data_gabungan_papua.csv', index=False)
display(df_final_pulau)

None

          keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_papua    3070134    2754391            5824525