In [1]:
import pandas as pd
import json

In [2]:
file_provinsi = {
    'jumlah_penduduk_dki_jakarta.csv': 'dki_jakarta',
    'jumlah_penduduk_jawa_barat.csv': 'jawa_barat',
    'jumlah_penduduk_jawa_tengah.csv': 'jawa_tengah',
    'jumlah_penduduk_yogyakarta.csv': 'di_yogyakarta',
    'jumlah_penduduk_jawa_timur.csv': 'jawa_timur'
}

list_df = []

for filename, provinsi in file_provinsi.items():
    df_merge = pd.read_csv(filename)
    df_flat = pd.DataFrame([{
        'provinsi': provinsi,
        'laki_laki': int(df_merge['laki_laki'].iloc[0]),
        'perempuan': int(df_merge['perempuan'].iloc[0]),
        'total_keseluruhan': int(df_merge['total_keseluruhan'].iloc[0])
    }])
    list_df.append(df_flat)

df_merge_jawa = pd.concat(list_df, ignore_index=True)

display(df_merge_jawa)

        provinsi  laki_laki  perempuan  total_keseluruhan
0    dki_jakarta    5360827    5317148           10677975
1     jawa_barat   25682100   25076900           50759000
2    jawa_tengah   19203434   19030499           38233933
3  di_yogyakarta    1870100    1911400            3781500
4     jawa_timur   20978500   21110800           42089300

In [5]:
total_laki_gabungan = int(df_merge_jawa['laki_laki'].sum())
total_perempuan_gabungan = int(df_merge_jawa['perempuan'].sum())
total_gabungan_keseluruhan = int(df_merge_jawa['total_keseluruhan'].sum())

df_total_pulau = pd.DataFrame([{
    'provinsi': 'total_pulau_jawa',
    'laki_laki': total_laki_gabungan,
    'perempuan': total_perempuan_gabungan,
    'total_keseluruhan': total_gabungan_keseluruhan
}])

df_final = pd.concat([df_merge_jawa, df_total_pulau], ignore_index=True)

display(df_final)

           provinsi  laki_laki  perempuan  total_keseluruhan
0       dki_jakarta    5360827    5317148           10677975
1        jawa_barat   25682100   25076900           50759000
2       jawa_tengah   19203434   19030499           38233933
3     di_yogyakarta    1870100    1911400            3781500
4        jawa_timur   20978500   21110800           42089300
5  total_pulau_jawa   73094961   72446747          145541708

In [6]:
df_final.to_csv('data_penduduk_jawa.csv', index=False)
df_final.to_json('data_penduduk_jawa.json', orient='records')

In [8]:
total_laki_pulau = 0
total_perempuan_pulau = 0

for filename in file_provinsi:
    df_temp = pd.read_csv(filename)
    total_laki_pulau += int(df_temp['laki_laki'].iloc[0])
    total_perempuan_pulau += int(df_temp['perempuan'].iloc[0])

total_keseluruhan_pulau = total_laki_pulau + total_perempuan_pulau

df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_pulau_jawa',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

json_output = df_final_pulau.to_json('data_gabungan_jawa.json', orient='records')
print(json_output)

csv_output = df_final_pulau.to_csv('data_gabungan_jawa.csv', index=False)
display(df_final_pulau)

None

         keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_jawa   73094961   72446747          145541708