In [ ]:
import pandas as pd

file_provinsi = [
    'jumlah_penduduk_kalimantan_barat.csv',
    'jumlah_penduduk_kalimantan_tengah.csv',
    'jumlah_penduduk_kalimantan_selatan.csv',
    'jumlah_penduduk_kalimantan_timur.csv',
    'jumlah_penduduk_kalimantan_utara.csv'
]

data_kalimantan = []

total_laki = 0
total_perempuan = 0

for file in file_provinsi:

    df = pd.read_csv(file)

    laki = int(df['laki_laki'].iloc[0])
    perempuan = int(df['perempuan'].iloc[0])

    total_keseluruhan = laki + perempuan

    nama_provinsi = (
        file
        .replace('jumlah_penduduk_', '')
        .replace('.csv', '')
    )

    data_kalimantan.append({
        'provinsi': nama_provinsi,
        'laki_laki': laki,
        'perempuan': perempuan,
        'total_keseluruhan': total_keseluruhan
    })

    total_laki += laki
    total_perempuan += perempuan

total_pulau = total_laki + total_perempuan

data_kalimantan.append({
    'provinsi': 'total_pulau_kalimantan',
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_pulau
})

df_final = pd.DataFrame(data_kalimantan)

display(df_final)

df_final.to_csv(
    'data_penduduk_kalimantan.csv',
    index=False
)

df_final.to_json(
    'data_penduduk_kalimantan.json',
    orient='records',
    indent=4
)

                 provinsi  laki_laki  perempuan  total_keseluruhan
0        kalimantan_barat    2957074    2808956            5766030
1       kalimantan_tengah    1450000    1370000            2820000
2      kalimantan_selatan    2185000    2138330            4323330
3        kalimantan_timur    1998730    1880778            3879508
4        kalimantan_utara     389219     356237             745456
5  total_pulau_kalimantan    8980023    8554301           17534324

In [71]:
import pandas as pd

file_provinsi = [
    'jumlah_penduduk_kalimantan_barat.csv',
    'jumlah_penduduk_kalimantan_tengah.csv',
    'jumlah_penduduk_kalimantan_selatan.csv',
    'jumlah_penduduk_kalimantan_timur.csv',
    'jumlah_penduduk_kalimantan_utara.csv'
]
data_sumatera = []


total_laki = 0
total_perempuan = 0


for file in file_provinsi:

    df = pd.read_csv(file)

    laki = int(df['laki_laki'].iloc[0])
    perempuan = int(df['perempuan'].iloc[0])
    total = int(df['total_keseluruhan'].iloc[0])

    nama_provinsi = file.replace('.csv', '')


    data_sumatera.append({
        'provinsi': nama_provinsi,
        'laki_laki': laki,
        'perempuan': perempuan,
        'total_keseluruhan': total
    })


    total_laki += laki
    total_perempuan += perempuan


total_pulau = total_laki + total_perempuan


data_kalimantan.append({
    'provinsi': 'total_pulau_kalimantan',
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_pulau
})


df_final = pd.DataFrame(data_kalimantan)

display(df_final)


df_final.to_csv(
    'data_penduduk_kalimantan.csv',
    index=False
)


df_final.to_json(
    'data_penduduk_kalimantan.json',
    orient='records',
    indent=4
)

                 provinsi  laki_laki  perempuan  total_keseluruhan
0        kalimantan_barat    2957074    2808956            5766030
1       kalimantan_tengah    1450000    1370000            2820000
2      kalimantan_selatan    2185000    2138330            4323330
3        kalimantan_timur    1998730    1880778            3879508
4        kalimantan_utara     389219     356237             745456
5  total_pulau_kalimantan    8980023    8554301           17534324
6  total_pulau_kalimantan    8980023    8554301           17534324
7  total_pulau_kalimantan    8980023    8554301           17534324

In [72]:
import pandas as pd

file_provinsi = [
   'jumlah_penduduk_kalimantan_barat.csv',
    'jumlah_penduduk_kalimantan_tengah.csv',
    'jumlah_penduduk_kalimantan_selatan.csv',
    'jumlah_penduduk_kalimantan_timur.csv',
    'jumlah_penduduk_kalimantan_utara.csv'
]


total_laki_pulau = 0
total_perempuan_pulau = 0


for filename in file_provinsi:
    df_temp = pd.read_csv(filename)

    total_laki_pulau += int(
        df_temp['laki_laki'].iloc[0]
    )

    total_perempuan_pulau += int(
        df_temp['perempuan'].iloc[0]
    )


total_keseluruhan_pulau = (
    total_laki_pulau + total_perempuan_pulau
)

# dataframe final pulau
df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_pulau_kalimantan',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

display(df_final_pulau)


df_final_pulau.to_json(
    'data_gabungan_kalimantan.json',
    orient='records',
    indent=4
)


df_final_pulau.to_csv(
    'data_gabungan_kalimantan.csv',
    index=False
)

               keterangan  laki_laki  perempuan  total_keseluruhan
0  total_pulau_kalimantan    8980023    8554301           17534324