## **IMPORT LIBRARY**

In [1]:
import pandas as pd

# DATA WRANGLING

## **LOAD DATA**

In [2]:
df = pd.read_csv("kamus_perbandingan_nusantaralens (1).csv")
display(df)

   Indonesia                         Jawa    Aceh   Abui
0       adik                 adhi; unting    adek  kokda
1        air                  banyu; toya      ie     ya
2        apa                          apa    peue   nala
3       asin                         asin   masen    NaN
4       ayam                  ayam; pitik  manoek  ruwol
..       ...                          ...     ...    ...
86      uang          arta; dhuwit; yaksa    peng   seng
87      ulat                         uler    ulat    NaN
88      umur                  umur; yamèn     umu    NaN
89     waktu  yèn; yeng-yengan; yer-yeran   watèe    NaN
90      yang                      ingkang   nyang     ba

[91 rows x 4 columns]

In [3]:
print("Mengecek tipe data kamus")
display(df.info())

Mengecek tipe data kamus
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Indonesia  91 non-null     object
 1   Jawa       91 non-null     object
 2   Aceh       91 non-null     object
 3   Abui       56 non-null     object
dtypes: object(4)
memory usage: 3.0+ KB

None

In [4]:
df_cleaned = df.apply(lambda x: x.str.strip() if x.dtype=='object' else x)

df_cleaned = df_cleaned.replace(';' , ',', regex=True)
display(df_cleaned)

   Indonesia                         Jawa    Aceh   Abui
0       adik                 adhi, unting    adek  kokda
1        air                  banyu, toya      ie     ya
2        apa                          apa    peue   nala
3       asin                         asin   masen    NaN
4       ayam                  ayam, pitik  manoek  ruwol
..       ...                          ...     ...    ...
86      uang          arta, dhuwit, yaksa    peng   seng
87      ulat                         uler    ulat    NaN
88      umur                  umur, yamèn     umu    NaN
89     waktu  yèn, yeng-yengan, yer-yeran   watèe    NaN
90      yang                      ingkang   nyang     ba

[91 rows x 4 columns]

In [5]:
display(df_cleaned.describe())

display(df_cleaned.isna().sum())

display(df_cleaned.duplicated().sum())

       Indonesia          Jawa  Aceh   Abui
count         91            91    91     56
unique        91            91    91     56
top         adik  adhi, unting  adek  kokda
freq           1             1     1      1

Indonesia     0
Jawa          0
Aceh          0
Abui         35
dtype: int64

np.int64(0)

In [6]:
columns = ['Aceh','Jawa', 'Abui']

for col in columns:
    kamus_pisah = df_cleaned[['Indonesia', col]]
    kamus_pisah = kamus_pisah.dropna()
    file = f'{col}.csv'
    kamus_pisah.to_csv(file, index=False)
    print(f'Berhasil Menyimpan {file}')

Berhasil Menyimpan Aceh.csv
Berhasil Menyimpan Jawa.csv
Berhasil Menyimpan Abui.csv

In [14]:
tampung_data = {}
daftar_file = ['Aceh', 'Jawa', 'Abui']

for tabel in daftar_file:
    df = f'{tabel}.csv'
    tampung_data[tabel] = pd.read_csv(df)
    print(f'Berhasil Load tabel dari {df}')

Berhasil Load tabel dari Aceh.csv
Berhasil Load tabel dari Jawa.csv
Berhasil Load tabel dari Abui.csv

In [18]:
for nama, df in tampung_data.items():
    print(f'Tabel Bahasa {nama}')
    print(f'Jumlah baris kolom {df.shape}' )
    print(f'Informasi tabel {nama} adalah {df.info()}')

Tabel Bahasa Aceh
Jumlah baris kolom (91, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Indonesia  91 non-null     object
 1   Aceh       91 non-null     object
dtypes: object(2)
memory usage: 1.6+ KB
Informasi tabel Aceh adalah None
Tabel Bahasa Jawa
Jumlah baris kolom (91, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Indonesia  91 non-null     object
 1   Jawa       91 non-null     object
dtypes: object(2)
memory usage: 1.6+ KB
Informasi tabel Jawa adalah None
Tabel Bahasa Abui
Jumlah baris kolom (56, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Indonesia  56 non-null     object
 1   Abui       56 non-null     object
dtypes: object(2)
memory usage: 1.0+ KB
Informasi tabel Abui adalah None