In [1]:
import pandas as pd
import json

In [3]:
file_provinsi = {
    'jumlah_penduduk_babel.csv': 'bangka_belitung'
}

list_df = []

for filename, provinsi in file_provinsi.items():
    df_merge = pd.read_csv(filename)
    df_flat = pd.DataFrame([{
        'provinsi': provinsi,
        'laki_laki': int(df_merge['laki_laki'].iloc[0]),
        'perempuan': int(df_merge['perempuan'].iloc[0]),
        'total_keseluruhan': int(df_merge['total_keseluruhan'].iloc[0])
    }])
    list_df.append(df_flat)

df_merge_babel= pd.concat(list_df, ignore_index=True)

display(df_merge_babel)

          provinsi  laki_laki  perempuan  total_keseluruhan
0  bangka_belitung     795200     755600            1550800

In [5]:
total_laki_gabungan = int(df_merge_babel['laki_laki'].sum())
total_perempuan_gabungan = int(df_merge_babel['perempuan'].sum())
total_gabungan_keseluruhan = int(df_merge_babel['total_keseluruhan'].sum())

df_total_pulau = pd.DataFrame([{
    'provinsi': 'total_bangka_belitung',
    'laki_laki': total_laki_gabungan,
    'perempuan': total_perempuan_gabungan,
    'total_keseluruhan': total_gabungan_keseluruhan
}])

df_final = pd.concat([df_merge_babel, df_total_pulau], ignore_index=True)

display(df_final)

                provinsi  laki_laki  perempuan  total_keseluruhan
0        bangka_belitung     795200     755600            1550800
1  total_bangka_belitung     795200     755600            1550800

In [6]:
df_final.to_csv('data_penduduk_bangka_belitung.csv', index=False)
df_final.to_json('data_penduduk_bangka_belitung.json', orient='records')

In [7]:
total_laki_pulau = 0
total_perempuan_pulau = 0

for filename in file_provinsi:
    df_temp = pd.read_csv(filename)
    total_laki_pulau += int(df_temp['laki_laki'].iloc[0])
    total_perempuan_pulau += int(df_temp['perempuan'].iloc[0])

total_keseluruhan_pulau = total_laki_pulau + total_perempuan_pulau

df_final_pulau = pd.DataFrame([{
    'keterangan': 'total_bangka_belitung',
    'laki_laki': total_laki_pulau,
    'perempuan': total_perempuan_pulau,
    'total_keseluruhan': total_keseluruhan_pulau
}])

json_output = df_final_pulau.to_json('data_gabungan_bangka_belitung.json', orient='records')
print(json_output)

csv_output = df_final_pulau.to_csv('data_gabungan_bangka_belitung.csv', index=False)
display(df_final_pulau)

None

              keterangan  laki_laki  perempuan  total_keseluruhan
0  total_bangka_belitung     795200     755600            1550800